In [1]:
import pandas as pd

In [18]:
df=pd.read_csv(r'C:\Users\janha\OneDrive\Desktop\CC REPORT\cc_add.csv')

In [25]:
df

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Ct,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,963607849,Blue,300,1,108,2023-12-31,Week-53,Q4,2023,14315.0,690,9603,56,0.048,Swipe,Entertainment,598.69,0
1,932954954,Blue,175,1,96,2023-12-31,Week-53,Q4,2023,5711.0,0,4325,72,0.000,Swipe,Fuel,691.20,0
2,961650885,Blue,195,0,76,2023-12-31,Week-53,Q4,2023,3104.0,1766,9353,24,0.569,Swipe,Travel,216.48,0
3,917695309,Blue,495,1,72,2023-12-31,Week-53,Q4,2023,2553.0,1823,3853,69,0.714,Chip,Grocery,1001.78,0
4,957309271,Blue,100,0,172,2023-12-31,Week-53,Q4,2023,2476.0,1944,4025,65,0.785,Chip,Fuel,845.25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,964474458,Blue,100,0,72,2023-12-31,Week-53,Q4,2023,1438.3,0,4928,84,0.000,Online,Grocery,788.48,0
181,962482385,Silver,100,1,150,2023-12-31,Week-53,Q4,2023,34516.0,2052,3510,62,0.059,Swipe,Grocery,772.20,0
182,919695363,Blue,475,1,99,2023-12-31,Week-53,Q4,2023,3807.0,2517,19739,36,0.661,Swipe,Entertainment,504.31,0
183,931822111,Blue,275,0,99,2023-12-31,Week-53,Q4,2023,11548.0,0,7781,72,0.000,Swipe,Food,1167.15,0
184,925168075,Blue,245,1,74,2023-12-31,Week-53,Q4,2023,20769.0,901,1835,43,0.043,Chip,Fuel,201.85,0

In [26]:
df.to_csv(r'C:\Users\janha\OneDrive\Desktop\CC REPORT\cc_add.csv',index=False)

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\janha\\OneDrive\\Desktop\\CC REPORT\\cc_add.csv'

In [27]:
df.to_csv(r"C:\Users\janha\OneDrive\Desktop\CC REPORT\cc_add_new.csv", index=False)